version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: venkat
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: venkat_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-python-app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: